### ISSUE TITLE
PJSIP python

### ISSUE THREAD

**Issue by wayne-david** [pjsip/pjproject_docs#19]
Having trouble with the pjsip in python and viirtue sip server.I have attempted the pygui example but SIP registration times out.Is pjsip compatible with viirtue or is it a configurations issue.Any help will be appreciated
![pjsip](https://github.com/pjsip/pjproject_docs/assets/40905642/37de037a-3152-4333-910a-27921b316662)

My configuration is as follows
![image](https://github.com/pjsip/pjproject_docs/assets/40905642/1be46235-40a5-41fa-9662-20d9d0a1ab4d)
![image](https://github.com/pjsip/pjproject_docs/assets/40905642/d52e6137-ee27-4654-9a81-6e469c6f87fa)
![image](https://github.com/pjsip/pjproject_docs/assets/40905642/a04bf209-111f-402e-9f32-47a4ed33787b)

**Comment by sauwming** [comment]
Check the server log, if it receives the request and respond accordingly.

This is not the place to ask enquiries. Any future issue opened will be immediately closed.
